# Generated by Django 4.2 on 2026-01-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_country_user_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='other', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='learning_language_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
