# Generated by Django 4.2 on 2026-01-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_gender_user_learning_language_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingotp',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
