# Generated by Django 4.2 on 2026-01-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_pendingotp_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetotp',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
