# Generated by Django 4.2 on 2026-01-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_passwordresetotp_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetotp',
            name='last_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
