# Generated by Django 4.2 on 2026-01-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_passwordresetotp_last_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetotp',
            name='identifier',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='pendingotp',
            name='identifier',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
