# Generated by Django 4.2 on 2026-01-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_passwordresetotp_identifier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingotp',
            name='last_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingotp',
            name='resend_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
