# Generated by Django 4.2 on 2026-01-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_pendingotp_last_sent_at_pendingotp_resend_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetotp',
            name='resend_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
